# Generated by Django 4.2.7 on 2023-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[("J", "Job"), ("O", "Other")], default="O", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(),
        ),
    ]
