# Generated by Django 4.2.7 on 2023-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_post_created_at_post_title_post_type_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(choices=[("J", "Job"), ("O", "Other")], default="O"),
        ),
    ]
