# Generated by Django 4.2.7 on 2023-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_profile_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=models.FileField(blank=True, default=None, upload_to="resumes"),
        ),
    ]
