# Generated by Django 4.2.7 on 2023-11-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_profile_first_name_alter_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="./profile/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=models.FileField(blank=True, default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("jobseeker", "Job Seeker"), ("recruiter", "Recruiter")],
                max_length=150,
                null=True,
            ),
        ),
    ]
