# Generated by Django 4.2.7 on 2023-11-28 05:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_recruiterprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region="IN", unique=True
            ),
        ),
    ]
