# Generated by Django 4.2.7 on 2024-01-07 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=256)),
                ("company", models.CharField(max_length=256)),
                (
                    "workplace_type",
                    models.CharField(
                        choices=[
                            ("on-site", "On-Site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                        ],
                        help_text="Select the work place type.",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("volunteer", "Volunteer"),
                            ("intership", "Internship"),
                            ("other", "Other"),
                        ],
                        help_text="Select type of job.",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
