# Generated by Django 4.2.7 on 2024-01-08 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_job_delete_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="_type",
            new_name="job_type",
        ),
    ]
