# Generated by Django 4.2.7 on 2024-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_rename__type_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(
                help_text="Enter your company name.", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                help_text="Enter the description of the job such as skills, experience ..etc"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_title",
            field=models.CharField(
                help_text="Enter Job title that you are hiring.", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(help_text="Enter work location.", max_length=200),
        ),
    ]
